%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Matlab codees for 3D Anthropometry and Digital Human Modeling
%
% Wonsup Lee (mcury83@gmail.com)
% 01 Mar 2017
%
% This is open source. Anyone can freely use this codes without getting any
% permition from me. But, part of source code might hvae own license by its
% author (see if mentioned in each m-file).
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear; % delete all variables
clc; % clear command line window
close all; % close all figures


%% settings
save_outputs = 0;
    % 0: outputs will NOT be saved in files
    % 1: outputs will be saved
if save_outpus == 1
    mkdir('output');
end


%% data loading for one subject
dir = 'source 3D images';
filename = 'face_W.ply';
filename_3D_scan = fullfile(dir, filename);
[ListVertex, ListFace, ListFace_backup, HEADER] = ...
    function_loading_ply_file(filename_3D_scan);
    % If a PLY is not opening by this function, then check if the PLY is
    % binary format or not. Or the PLY might be written in different
    % format, that means this PLY loading function should be modified.

% Landmarks should be already marked on the 3D image by using any of 3D scan editing software.
% Then, landmarks should be saved as txt format (example: see 'face_W_landmark.asc').
% If data format is different than my example, the following code should be modified.
filename = 'face_W_landmark.asc';
filename_landmark = fullfile(dir, filename);
landmark = textread(filename_landmark, '');


%% landmark identification
% NOTE. Before run this code, the face should be roughly rotated to align
%       in X Y Z axis (Y-up). The face should faced to +Z direction
visualization = 0; % 1 = Yes || 0 = No
landmark = ...
    main_landmark_identification(ListFace, ListVertex, landmark, visualization); 
    % This code is only fit this example. If 

    
%% alignment
% The face will be aligned using two virtual axis.
% (1) A virtual axis generated by sellion(2) and supramentale(18) will be aligned to Y-axis.
% (2) A virtual axis generated by left and right zygion(12, 13) will be aligned to X-axis.

% pick 4 landmarks for alignment
reference.point1 = landmark{'sellion', :}; % point 1 & 2 will be aligned Y-axis
reference.point2 = landmark{'promentale', :};
reference.point3 = landmark{'zygion L', :}; % point 3 & 4 will be used to align the face with X-axis
reference.point4 = landmark{'zygion R', :};
origin = landmark('sellion', :);
visualization = 0; % 0 = No || 1 = Yes

[ListVertex, landmark] = ...
    function_alignment(reference, origin, ListFace, ListVertex, landmark, visualization);

% save modified 3D image (PLY file) and landmark table (.mat file)
if save_outputs == 1
    save('face_W_landmark.mat', 'landmark');
    filename_save = 'face_W_modified.ply';
    function_saving_ply_file(ListVertex, ListFace_backup, HEADER, filename_save);
end


%% facial measurement

% length dimensions (Euclidean distance)
subject_name = 'S1';
visualization = 1;
    % 0 = No
    % 1 = Yes
measurements = main_measurement(ListFace, ListVertex, landmark, subject_name, visualization);
%%% [ADD] add more facial dimensions to measure in function_measurement %%%


%%% [ADD]
% arc, circumference dimensions
% template registration
% symmetrization
% normal vector
% edge vector
% curvature
% shortest path
% landmarking
% trisurf
% regio growing
% outlier filtering